name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      runsOn:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean

jobs:
  run-tests:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore tests/UnitTests/UnitTests.csproj

      - name: Build project
        run: dotnet build tests/UnitTests/UnitTests.csproj --configuration ${{ inputs.configuration }} --no-restore

    
